Web/ITSkills.Web/Controllers/CategoriesController.cs
namespace ITSkills.Web.Controllers
{
    using ITSkills.Common;
    using ITSkills.Services.Data;
    using ITSkills.Web.ViewModels.Categories;

    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseController
    {
        private readonly ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public IActionResult ByName(string name)
        {
            if (!this.categoriesService.TryGetCategoryById<CategoryViewModel>(name))
            {
                return this.View(GlobalConstants.NotFoundRoute);
            }

            var viewModel = this.categoriesService.GetByName<CategoryViewModel>(name);
            return this.View(viewModel);
        }
    }
}

Web/ITSkills.Web/Controllers/LectionsController.cs
namespace ITSkills.Web.Controllers
{
    using ITSkills.Common;
    using ITSkills.Data.Models;
    using ITSkills.Services.Data;
    using ITSkills.Web.ViewModels.Courses;
    using ITSkills.Web.ViewModels.Lections;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class LectionsController : BaseController
    {
        private readonly ILectionsService lectionsService;
        private readonly IMyCoursesService myCoursesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICoursesService coursesService;

        public LectionsController(ILectionsService lectionsService, IMyCoursesService myCoursesService, UserManager<ApplicationUser> userManager, ICoursesService coursesService)
        {
            this.lectionsService = lectionsService;
            this.myCoursesService = myCoursesService;
            this.userManager = userManager;
            this.coursesService = coursesService;
        }

        [Authorize]
        public async Task<IActionResult> ById(int id)
        {
            if (!this.lectionsService.TryGetById<LectionsViewModel>(id))
            {
                return this.View(GlobalConstants.NotFoundRoute);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;

            if (!this.myCoursesService.IsHasPayed(userId))
            {
                return this.RedirectToAction("Payment", "Courses");
            }

            var lections = this.lectionsService.GetAll<ListLectionsViewModel>();
            var viewModel = this.lectionsService.GetById<LectionsViewModel>(id);
            viewModel.Lections = lections;
            return this.View(viewModel);
        }
    }
}

Web/ITSkills.Web/Views/Shared/NotFound.cshtml
<head>
    <title>Not Found</title>
</head>
<div class="text-center">
    <img src="~/img/artboard_1.png" class="center">
    <p>Hmm.. there's nothing here.</p>
    <style>
        img {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 30%;
        }

        p {
            color: black;
            font-size: 35px;
        }
    </style>
</div>

Web/ITSkills.Web/Views/Shared/NotLoggedIn.cshtml
<title>IT Skills</title>
<head>
    <script src="https://kit.fontawesome.com/e496302054.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/notLoggedIn.css" />
</head>
<body>
    <div class="main-content">
        <h1>Learn more now with IT Skills</h1>
        <div class="schedule">
            <span class="schedule">
                <i class="fas fa-history"></i>
                <span>Learn on your schedule;</span>
            </span>
        </div>
        <div class="courses">
            <span class="courses">
                <i class="fas fa-globe"></i>
                <span>Over hundreds of courses;</span>
            </span>
        </div>
        <div class="carousel-fullscreen-sidebar">
            <h2>What do you want to learn today?</h2>
            <form class="form-inline" asp-controller="Courses" asp-action="Index" method="get">
                <input class="form-control mr-sm-2" type="text" id="course-search-bar" placeholder="Search..." name="title">
                <button class="btn btn-outline-secondary my-2 my-sm-0" style="background-color: #fafafa;" type="submit"><i class="fas fa-search"></i></button>
            </form>
        </div>
</body>

Web/ITSkills.Web/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
@*<link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">*@
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

Web/ITSkills.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ITSkills</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <partial name="_Favicons" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 navbar-custom">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="logo" src="~/img/Logo.png" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="fas fa-bars"></i>
                    </span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <div class="w3-dropdown-hover">
                                <button class="w3-button">Administration</button>
                                <div class="w3-dropdown-content w3-bar-block w3-border">
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="Categories" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="Courses" asp-action="Index">Course</a>
                                    <a class="dropdown-item" asp-area="Administration" asp-controller="Lections" asp-action="Index">Lection</a>
                                </div>
                            </div>
                        }
                        <form class="form-inline" asp-controller="Courses" asp-action="Index" method="get">
                            <input class="form-control mr-sm-2" type="text" id="course-search-bar" placeholder="Search..." name="title">
                            <button class="btn btn-outline-secondary my-2 my-sm-0" style="background-color: #fafafa;" type="submit">Search</button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ITSkills - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <h7>Based on &copy;<a href="https://www.udemy.com">Udemy</a> </h7><h7>and &copy;<a href="https://www.softuni.bg">SoftUni</a></h7>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>